// <auto-generated />
using System;
using FantasyFootballManager.DataService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FantasyFootballManager.DataService.Migrations
{
    [DbContext(typeof(FantasyDbContext))]
    [Migration("20250725193349_IncreaseColumnSizes")]
    partial class IncreaseColumnSizes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FantasyFootballManager.DataService.Models.DataStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DataStatus");
                });

            modelBuilder.Entity("FantasyFootballManager.DataService.Models.FantasyActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDraftedOnMyTeam")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDraftedOnOtherTeam")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsThumbsDown")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsThumbsUp")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("FantasyActivities");
                });

            modelBuilder.Entity("FantasyFootballManager.DataService.Models.FantasyProsPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CbsPlayerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "cbs_player_id");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlayerByeWeek")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasAnnotation("Relational:JsonPropertyName", "player_bye_week");

                    b.Property<string>("PlayerEligibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "player_eligibility");

                    b.Property<string>("PlayerFilename")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasAnnotation("Relational:JsonPropertyName", "player_filename");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "player_id");

                    b.Property<string>("PlayerImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasAnnotation("Relational:JsonPropertyName", "player_image_url");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasAnnotation("Relational:JsonPropertyName", "player_name");

                    b.Property<double>("PlayerOwnedAvg")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "player_owned_avg");

                    b.Property<double>("PlayerOwnedEspn")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "player_owned_espn");

                    b.Property<int>("PlayerOwnedYahoo")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "player_owned_yahoo");

                    b.Property<string>("PlayerPageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasAnnotation("Relational:JsonPropertyName", "player_page_url");

                    b.Property<string>("PlayerPositionId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "player_position_id");

                    b.Property<string>("PlayerPositions")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "player_positions");

                    b.Property<string>("PlayerShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "player_short_name");

                    b.Property<string>("PlayerSquareImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasAnnotation("Relational:JsonPropertyName", "player_square_image_url");

                    b.Property<string>("PlayerTeamId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "player_team_id");

                    b.Property<string>("PlayerYahooId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "player_yahoo_id");

                    b.Property<string>("PlayerYahooPositions")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "player_yahoo_positions");

                    b.Property<string>("PosRank")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "pos_rank");

                    b.Property<string>("RankAve")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "rank_ave");

                    b.Property<int>("RankEcr")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "rank_ecr");

                    b.Property<string>("RankMax")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "rank_max");

                    b.Property<string>("RankMin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "rank_min");

                    b.Property<string>("RankStd")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "rank_std");

                    b.Property<string>("SportsdataId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "sportsdata_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "tier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("FantasyProsPlayers");
                });

            modelBuilder.Entity("FantasyFootballManager.DataService.Models.SleeperPlayer", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "player_id");

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "age");

                    b.Property<string>("BirthCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "birth_country");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "birth_date");

                    b.Property<string>("College")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasAnnotation("Relational:JsonPropertyName", "college");

                    b.Property<int?>("DepthChartOrder")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "depth_chart_order");

                    b.Property<string>("DepthChartPosition")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasAnnotation("Relational:JsonPropertyName", "depth_chart_position");

                    b.Property<int?>("EspnId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "espn_id");

                    b.Property<int?>("FantasyDataId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "fantasy_data_id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "first_name");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasAnnotation("Relational:JsonPropertyName", "full_name");

                    b.Property<string>("GsisId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "gsis_id");

                    b.Property<string>("Hashtag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "hashtag");

                    b.Property<string>("Height")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "height");

                    b.Property<string>("HighSchool")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasAnnotation("Relational:JsonPropertyName", "high_school");

                    b.Property<string>("InjuryBodyPart")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "injury_body_part");

                    b.Property<string>("InjuryNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasAnnotation("Relational:JsonPropertyName", "injury_notes");

                    b.Property<string>("InjuryStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "injury_status");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "active");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "last_name");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("NewsUpdated")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "news_updated");

                    b.Property<int?>("Number")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "number");

                    b.Property<string>("Position")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "position");

                    b.Property<int?>("RotowireId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "rotowire_id");

                    b.Property<int?>("RotoworldId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "rotoworld_id");

                    b.Property<string>("SearchFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "search_first_name");

                    b.Property<string>("SearchFullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasAnnotation("Relational:JsonPropertyName", "search_full_name");

                    b.Property<string>("SearchLastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "search_last_name");

                    b.Property<int?>("SearchRank")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "search_rank");

                    b.Property<string>("SportRadarId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "sportradar_id");

                    b.Property<int?>("StatsId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "stats_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<int?>("SwishId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "swish_id");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Weight")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "weight");

                    b.Property<int?>("YahooId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "yahoo_id");

                    b.Property<int?>("YearsExp")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "years_exp");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("SleeperPlayers");
                });

            modelBuilder.Entity("FantasyFootballManager.DataService.Models.SportsDataIoPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AuctionValue")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "AuctionValue");

                    b.Property<double?>("AuctionValuePPR")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "AuctionValuePPR");

                    b.Property<double?>("AverageDraftPosition")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "AverageDraftPosition");

                    b.Property<double?>("AverageDraftPosition2QB")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "AverageDraftPosition2QB");

                    b.Property<double?>("AverageDraftPositionDynasty")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "AverageDraftPositionDynasty");

                    b.Property<double?>("AverageDraftPositionIDP")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "AverageDraftPositionIDP");

                    b.Property<double?>("AverageDraftPositionPPR")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "AverageDraftPositionPPR");

                    b.Property<double?>("AverageDraftPositionRookie")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "AverageDraftPositionRookie");

                    b.Property<int?>("ByeWeek")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "ByeWeek");

                    b.Property<string>("FantasyPlayerKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "FantasyPlayerKey");

                    b.Property<double?>("LastSeasonFantasyPoints")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "LastSeasonFantasyPoints");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasAnnotation("Relational:JsonPropertyName", "Name");

                    b.Property<int>("PlayerID")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "PlayerID");

                    b.Property<int?>("PlayerTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "Position");

                    b.Property<double?>("ProjectedFantasyPoints")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "ProjectedFantasyPoints");

                    b.HasKey("Id");

                    b.HasIndex("PlayerTeamId");

                    b.ToTable("SportsDataIoPlayers");
                });

            modelBuilder.Entity("FantasyFootballManager.DataService.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("FantasyFootballManager.DataService.Models.FantasyProsPlayer", b =>
                {
                    b.HasOne("FantasyFootballManager.DataService.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FantasyFootballManager.DataService.Models.SleeperPlayer", b =>
                {
                    b.HasOne("FantasyFootballManager.DataService.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FantasyFootballManager.DataService.Models.SportsDataIoPlayer", b =>
                {
                    b.HasOne("FantasyFootballManager.DataService.Models.Team", "PlayerTeam")
                        .WithMany()
                        .HasForeignKey("PlayerTeamId");

                    b.Navigation("PlayerTeam");
                });
#pragma warning restore 612, 618
        }
    }
}
