apiVersion: v1
kind: Service
metadata:
  name: ffootballmanager-api
  namespace: ffootballmanager
  labels:
    app: ffootballmanager-api
    kubernetes.io/service-name: fantasyfootballmanagerapi-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: ffootballmanager-api