apiVersion: apps/v1
kind: Deployment
metadata:
  name: fantasyfootballmanager-api
  namespace: ffootballmanager
  labels:
    app: ffootballmanager-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ffootballmanager-api
  template:
    metadata:
      labels:
        app: ffootballmanager-api
    spec:
      containers:
      - name: fantasyfootballmanager
        image: ghcr.io/ckriutz/fantasyfootballmanager-api:latest
        imagePullPolicy: Always
        env:
        - name: sqlConnectionString
          valueFrom:
            configMapKeyRef:
              name: fantasy-football-config
              key: sqlConnectionString
        - name: redisOMConnectionString
          valueFrom:
            configMapKeyRef:
              name: fantasy-football-config
              key: redisOMConnectionString
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: fantasy-football-config
              key: REACT_APP_API_URL
        ports:
        - containerPort: 8080