// <auto-generated />
using System;
using FantasyFootballManager.Functions.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FantasyFootballManager_Functions.Migrations
{
    [DbContext(typeof(FantasyContext))]
    partial class FantasyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FantasyFootballManager.Functions.Models.FootballPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionValue")
                        .HasColumnType("integer");

                    b.Property<double>("AverageDraftPositionFCalculator")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageDraftPositionSportsData")
                        .HasColumnType("double precision");

                    b.Property<int>("Bye")
                        .HasColumnType("integer");

                    b.Property<int>("FFCRank")
                        .HasColumnType("integer");

                    b.Property<int>("FantasyProsId")
                        .HasColumnType("integer");

                    b.Property<int>("FantasyProsRank")
                        .HasColumnType("integer");

                    b.Property<int>("FootballCalculatorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnMyTeam")
                        .HasColumnType("boolean");

                    b.Property<double>("LastSeasonFantasyPoints")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LastUpdatedFFootballCalculator")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedFantasyPros")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedLineups")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedSportsDataIO")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PlayerHeadshotURL")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<double>("ProjectedFantasyPoints")
                        .HasColumnType("double precision");

                    b.Property<int>("SportsDataIOId")
                        .HasColumnType("integer");

                    b.Property<string>("Team")
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FootballPlayers");
                });

            modelBuilder.Entity("FantasyFootballManager.Functions.Models.ImportStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Service")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ImportStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
