# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  fantasyfootballmanagerweb:
    image: fantasyfootballmanagerweb
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5221:5221
    environment:
      - apiurl=[apiurl]
      - code=[code]
