name: Api Docker Build and Push

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

on:
    push:
        branches: [ "main" ]
        paths:
          - 'FantasyFootballManager.Api/**'

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./FantasyFootballManager.Api
        permissions:
            contents: read
            packages: write
        steps:
        - uses: actions/checkout@v3
        - name: Set up .NET 8
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: '8.0.x'
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Build and publish Docker image
          run: dotnet publish /t:PublishContainer -r linux-arm64
        - name: change image tag
          run: docker tag wowshop 'ghcr.io/ckriutz/fantasyfootballmanager:api-latest'

        - name: 'Build Inventory Image'
          run: docker push ghcr.io/ckriutz/fantasyfootballmanager:api-latest

        #- name: Log into registry
        #  uses: docker/login-action@v2.2.0
        #  with:
        #    registry: ${{ env.REGISTRY }}
        #    username: ${{ github.actor }}
        #    password: ${{ secrets.GITHUB_TOKEN }}

        #- name: Extract metadata (tags, labels) for Docker
        #  id: meta
        #  uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        #  with:
        #      images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        #- name: Build and push Docker image
        #  uses: docker/build-push-action@v5.3.0
        #  with:
        #    context: "{{defaultContext}}:FantasyFootballManager.Api"
        #    platforms: linux/arm64
        #    push: true
        #    tags: |
        #        ghcr.io/ckriutz/fantasyfootballmanager:api-latest
        #        ghcr.io/ckriutz/fantasyfootballmanager:api.${{ github.sha }}
        #    labels: ${{ steps.meta.outputs.tags }}