name: Deploy Functions

on:
  push:
      branches: [main]

env:
  AZURE_FUNCTIONAPP_NAME: ckriutzffootballfunctions  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'FantasyFootballManager.Functions'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    #defaults:
    #    run:
    #      working-directory: FantasyFootballManager.Functions
    environment: dev
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # Run dotnet  build and publish
    - name: 'Restore, Build, and Publish'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o ./output
        popd
    - name: List Files After Publish
      run: |
        pwd
        ls -a
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}