name: Node API Docker Build and Push

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

on:
    push:
        branches: [ "main" ]
        paths:
          - 'api/**'

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./api
        permissions:
            contents: read
            packages: write
        steps:
          - uses: actions/checkout@v3
          - name: Set up .NET 8
            uses: actions/setup-dotnet@v2
            with:
              dotnet-version: '8.0.x'
          - name: Restore dependencies
            run: dotnet restore
          - name: Build
            run: dotnet build --no-restore
          - name: Build and publish Docker image
            run: dotnet publish /t:PublishContainer -r linux-arm64
          - name: change image tag
            run: docker tag 'fantasyfootballmanager-api:latest' 'ghcr.io/ckriutz/fantasyfootballmanager:api-latest'
  
          - name: 'Build Inventory Image'
            run: docker push ghcr.io/ckriutz/fantasyfootballmanager:api-latest