name: Web Docker Build and Push

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

on:
    push:
        branches: [ "main" ]
        paths:
          - 'web/**'

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest     
        defaults:
            run:
                working-directory: ./web
        permissions:
            contents: read
            packages: write
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3.3.0
              with:
                platforms: linux/arm64
            - name: Log into registry
              uses: docker/login-action@v2.2.0
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v4.1.1
              with:
                context: "{{defaultContext}}:web"
                platforms: linux/arm64
                push: true
                build-args: |
                  REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}
                  REACT_APP_AUTH0_DOMAIN=${{ secrets.REACT_APP_AUTH0_DOMAIN }}
                  REACT_APP_AUTH0_CLIENT_ID=${{ secrets.REACT_APP_AUTH0_CLIENT_ID }}
                  REACT_APP_AUTH0_REDIRECT_URI=${{ secrets.REACT_APP_AUTH0_REDIRECT_URI }}
                tags: |
                      ghcr.io/ckriutz/fantasyfootballmanager-web:latest
                      ghcr.io/ckriutz/fantasyfootballmanager-web:${{ github.run_number }}
                labels: ${{ steps.meta.outputs.tags }}