apiVersion: apps/v1
kind: Deployment
metadata:
  name: fantasyfootballmanager-web
  namespace: ffootballmanager
spec:
  selector:
    matchLabels:
      app: fantasyfootballmanager-web
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: fantasyfootballmanager-web
    spec:
      containers:
      - name: fantasyfootballmanager
        image: ghcr.io/ckriutz/fantasyfootballmanager:web-latest
        imagePullPolicy: Always
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: fantasy-football-config
              key: REACT_APP_API_URL
        ports:
        - containerPort: 3000
